In [1]:
! pip3 install gym==0.21.0
! pip3 install gym-retro==0.8.0
#! pip3 install opencv-python==4.6.0.66
#! pip3 install stable-baselines3==1.7.0

In [2]:
import retro

In [3]:
! python3 -m retro.import .

Importing StreetFighterIISpecialChampionEdition-Genesis
Imported 1 games


In [4]:
retro.data.list_games()

['1942-Nes',
 '1943-Nes',
 '3NinjasKickBack-Genesis',
 '8Eyes-Nes',
 'AaahhRealMonsters-Genesis',
 'AbadoxTheDeadlyInnerWar-Nes',
 'AcceleBrid-Snes',
 'ActRaiser2-Snes',
 'ActionPachio-Snes',
 'AddamsFamily-GameBoy',
 'AddamsFamily-Genesis',
 'AddamsFamily-Nes',
 'AddamsFamily-Sms',
 'AddamsFamily-Snes',
 'AddamsFamilyPugsleysScavengerHunt-Nes',
 'AddamsFamilyPugsleysScavengerHunt-Snes',
 'AdvancedBusterhawkGleylancer-Genesis',
 'Adventure-Atari2600',
 'AdventureIsland-GameBoy',
 'AdventureIsland3-Nes',
 'AdventureIslandII-Nes',
 'AdventuresOfBatmanAndRobin-Genesis',
 'AdventuresOfBayouBilly-Nes',
 'AdventuresOfDinoRiki-Nes',
 'AdventuresOfDrFranken-Snes',
 'AdventuresOfKidKleets-Snes',
 'AdventuresOfMightyMax-Genesis',
 'AdventuresOfMightyMax-Snes',
 'AdventuresOfRockyAndBullwinkleAndFriends-Genesis',
 'AdventuresOfRockyAndBullwinkleAndFriends-Nes',
 'AdventuresOfRockyAndBullwinkleAndFriends-Snes',
 'AdventuresOfStarSaver-GameBoy',
 'AdventuresOfYogiBear-Snes',
 'AeroFighters-Snes',
 

In [12]:
# creating our game environment

env = retro.make(game="StreetFighterIISpecialChampionEdition-Genesis")

In [6]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [7]:
env.action_space

MultiBinary(12)

In [8]:
env.action_space.sample()

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0], dtype=int8)

In [17]:
import time

obs = env.reset() # Reset game to starting state

done = False # Set flag to flase, tells us when we dies
for game in range(1): # play one game 
    while not done: 
        if done: 
            obs = env.reset() # when we do die, we start the game again
        env.render()
        obs, reward, done, info = env.step(env.action_space.sample()) # randomly take action
        time.sleep(0.01)
        if reward > 0:
            print(reward) # only a number when win, no rewards when getting along which makes it hard to train rl agent - sparse rewards
        # need to change this, as the spare rewards will make it hard to train the rl agent

500.0
100.0
500.0
500.0
500.0
1500.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
1000.0
500.0
300.0
100.0
500.0
1000.0
500.0
500.0
500.0
500.0
1000.0
500.0
1500.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
1000.0
1000.0
10000.0
100.0
100.0
500.0
300.0
500.0


In [18]:
info

{'continuetimer': 10,
 'enemy_matches_won': 2,
 'enemy_health': 0,
 'health': 0,
 'matches_won': 0,
 'score': 27400}

In [23]:
env.close()

In [ ]:
#! pip3 install opencv-python==4.6.0.66

In [20]:
from gym import Env
from gym.spaces import MultiBinary, Box
import numpy as np # to calculate the delta between the frames
import cv2 # for grayscaling


Next steps to preprocess the environment
- Observation Preprocess - grayscale, frame delta, resize the frame so we have less pixels
- Filter the action - parameter 
- Reward function - set this to the score

In [21]:
# Creating custom environment that will carry out all the steps
# we pass our pass environment

# Code reference: https://github.com/nicknochnack/StreetFighterRL

class StreetFighter(Env): 
    def __init__(self):
        super().__init__()
        # Specify action space and observation space 
        # resizing and making gray scale
        self.observation_space = Box(low=0, high=255, shape=(84, 84, 1), dtype=np.uint8) 
        self.action_space = MultiBinary(12)
        # Startup and instance of the game 
        # additional parameter to filter only valid actions
        self.game = retro.make(game='StreetFighterIISpecialChampionEdition-Genesis', use_restricted_actions=retro.Actions.FILTERED)
    
    def reset(self):
        # Return the first frame 
        obs = self.game.reset()
        obs = self.preprocess(obs) 
        self.previous_frame = obs # want to also keep track of the previous frame to calculate a delta between the frames
        
        # Create a attribute to hold the score delta 
        self.score = 0 
        return obs
    
    def preprocess(self, observation): 
        # Grayscaling 
        gray = cv2.cvtColor(observation, cv2.COLOR_BGR2GRAY)
        # Resize 
        resize = cv2.resize(gray, (84,84), interpolation=cv2.INTER_CUBIC)
        # Add the channels value
        channels = np.reshape(resize, (84,84,1))
        return channels 
    
    def step(self, action): 
        # Take a step 
        obs, reward, done, info = self.game.step(action)
        obs = self.preprocess(obs) 
        
        # Frame delta - use this to train our agent
        frame_delta = obs - self.previous_frame
        self.previous_frame = obs 
        
        # Reshape the reward function
        reward = info['score'] - self.score 
        self.score = info['score'] 
        
        return frame_delta, reward, done, info
    
    def render(self, *args, **kwargs):
        self.game.render()
        
    def close(self):
        self.game.close()

In [24]:
env = StreetFighter()

In [25]:
env.observation_space

Box([[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]], [[[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 ...

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]], (84, 84, 1), uint8)

In [26]:
env.action_space.sample()

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1], dtype=int8)

In [27]:
import time

obs = env.reset() # Reset game to starting state

done = False # Set flag to flase, tells us when we dies
for game in range(1): # play one game 
    while not done: 
        if done: 
            obs = env.reset() # when we do die, we start the game again
        env.render()
        obs, reward, done, info = env.step(env.action_space.sample()) # randomly take action
        time.sleep(0.01)
        if reward > 0:
            print(reward) # only a number when win, no rewards when getting along which makes it hard to train rl agent - sparse rewards
        # need to change this, as the spare rewards will make it hard to train the rl agent

2024-06-08 10:57:12.378 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabaf4db2a0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 10:57:12.379 python[12151:36719507] Warning: Expected min height of view: (<NSButton: 0x7faba8c5bf00>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 10:57:12.383 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7faba8b71100>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 10:57:12.385 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7faba8b77330>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.


100
1000
500
500
300
300
300


KeyboardInterrupt: 

In [59]:
env.close()

In [ ]:
! pip3 install stable-baselines3==1.7.0

In [ ]:
! pip3 install torch torchvision

In [47]:
from stable_baselines3 import PPO

In [60]:
env = StreetFighter() # to create our preprocessed environment
model = PPO("CnnPolicy", env, verbose=1, learning_rate=0.000001, n_steps=512) # creating the model

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [61]:
# train the AI model on n steps

timesteps = 10000
model.learn(total_timesteps=timesteps)

----------------------------
| time/              |     |
|    fps             | 281 |
|    iterations      | 1   |
|    time_elapsed    | 1   |
|    total_timesteps | 512 |
----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 100          |
|    iterations           | 2            |
|    time_elapsed         | 10           |
|    total_timesteps      | 1024         |
| train/                  |              |
|    approx_kl            | 4.020869e-06 |
|    clip_fraction        | 0            |
|    clip_range           | 0.2          |
|    entropy_loss         | -8.32        |
|    explained_variance   | -0.00136     |
|    learning_rate        | 1e-06        |
|    loss                 | 2.58e+03     |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.000311    |
|    value_loss           | 4.23e+03     |
------------------------------------------
-----------------------

In [55]:
?PPO

Init signature:
PPO(
    policy: Union[str, Type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gym.core.Env, stable_baselines3.common.vec_env.base_vec_env.VecEnv, str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    normalize_advantage: bool = True,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    target_kl: Union[float, NoneType] = None,
    tensorboard_log: Union[str, NoneType] = None,
    policy_kwargs: Union[Dict[str, Any], NoneType] = None,
    verbose: int = 0,
    seed: Union[int, NoneType] = None,
    device: Union[torch.device, str] = 'auto',
    _init_setup_model: bool

In [63]:
# save the model
model.save(f"training/models/PPO_{timesteps}_SF_tuned")

In [64]:
del model

In [65]:
env.close()

In [66]:
# evaluate the model
from stable_baselines3.common.evaluation import evaluate_policy

# create environment
env = StreetFighter()
model = PPO.load(f"training/models/PPO_10000_SF_tuned")
mean_reward, _ = evaluate_policy(model, env, render=True, n_eval_episodes=5)


2024-06-08 11:38:57.679 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabad4c9760>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 11:38:57.681 python[12151:36719507] Warning: Expected min height of view: (<NSButton: 0x7fabad29a1b0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 11:38:57.684 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabad0b1990>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 11:38:57.686 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabaee06860>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.


In [67]:
mean_reward, _

(1000.0, 0.0)

In [68]:
! pip3 install torch torchvision optuna

In [72]:
# Hyperparameter tuning - very important when it comes to RL
# Function to return test hyperparameters - define the object function

# Importing the optimzation frame - HPO
import optuna

def optimize_ppo(trial): 
    return {
        'n_steps':trial.suggest_int('n_steps', 500, 1000),
        #'gamma':trial.suggest_loguniform('gamma', 0.8, 0.9999),
        'learning_rate':trial.suggest_loguniform('learning_rate', 1e-5, 1e-3),
        #'clip_range':trial.suggest_uniform('clip_range', 0.1, 0.4),
        #'gae_lambda':trial.suggest_uniform('gae_lambda', 0.8, 0.99)
    }

# https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html
# video: https://www.youtube.com/watch?v=6sNIDqgICLY

In [70]:
# Run a training loop and return mean reward 
def optimize_agent(trial):
    # create the experiment
    timesteps = 1000 # increase this + n_eval_episodes for smoother performance and number trials
    # do not hyperparameter tune on large timesteos though
    save_path = f"training/models/opt/PPO_{timesteps}_SF_{trial.number}"

    model_params = optimize_ppo(trial) 

    # Create environment 
    env = StreetFighter()

    # Create algo 
    model = PPO('CnnPolicy', env, tensorboard_log="training/Logs", verbose=1, **model_params)
    model.learn(total_timesteps=timesteps)

    # Evaluate model 
    mean_reward, _ = evaluate_policy(model, env, n_eval_episodes=5)
    env.close()

    model.save(save_path)

    return mean_reward


In [75]:
# Creating the experiment 
study = optuna.create_study(direction='maximize')
study.optimize(optimize_agent, n_trials=5, n_jobs=1) # training for n x number of steps
#study.optimize(optimize_agent, n_trials=100, n_jobs=1)

[I 2024-06-08 12:03:21,478] A new study created in memory with name: no-name-e1184ab5-f709-449f-a4da-80704250ca42
/var/folders/gs/c69h38_15hb4fnkpnc9gvksm0000gn/T/ipykernel_12151/1860016905.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate':trial.suggest_loguniform('learning_rate', 1e-5, 1e-3),
/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py:145: UserWarning: You have specified a mini-batch size of 64, but because the `RolloutBuffer` is of size `n_steps * n_envs = 894`, after every 13 untruncated mini-batches, there will be a truncated mini-batch of size 62
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=894 and n_envs=1)
  warnings.warn(


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Logging to training/Logs/PPO_23
----------------------------
| time/              |     |
|    fps             | 305 |
|    iterations      | 1   |
|    time_elapsed    | 2   |
|    total_timesteps | 894 |
----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 100        |
|    iterations           | 2          |
|    time_elapsed         | 17         |
|    total_timesteps      | 1788       |
| train/                  |            |
|    approx_kl            | 0.10323409 |
|    clip_fraction        | 0.401      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.22      |
|    explained_variance   | 0.000516   |
|    learning_rate        | 0.000221   |
|    loss                 | 2.02e+03   |
|    n_updates            | 10         |
|    policy_gra

/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
[I 2024-06-08 12:05:49,974] Trial 0 finished with value: 1400.0 and parameters: {'n_steps': 894, 'learning_rate': 0.00022100419431297886}. Best is trial 0 with value: 1400.0.
/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py:145: UserWarning: You have specified a mini-batch size of 64, but because the `RolloutBuffer` is of size `n_steps * n_envs = 998`, after every 15 untruncated mini-batches, there will be a truncated mini-batch of size 38
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=998 and n_envs=1)
  warnings.warn(


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Logging to training/Logs/PPO_24
----------------------------
| time/              |     |
|    fps             | 316 |
|    iterations      | 1   |
|    time_elapsed    | 3   |
|    total_timesteps | 998 |
----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 104        |
|    iterations           | 2          |
|    time_elapsed         | 19         |
|    total_timesteps      | 1996       |
| train/                  |            |
|    approx_kl            | 0.07395246 |
|    clip_fraction        | 0.278      |
|    clip_range           | 0.2        |
|    entropy_loss         | -8.29      |
|    explained_variance   | -0.000555  |
|    learning_rate        | 0.000179   |
|    loss                 | 248        |
|    n_updates            | 10         |
|    policy_gra

[I 2024-06-08 12:08:07,348] Trial 1 finished with value: 1600.0 and parameters: {'n_steps': 998, 'learning_rate': 0.00017923722073007344}. Best is trial 1 with value: 1600.0.
/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py:145: UserWarning: You have specified a mini-batch size of 64, but because the `RolloutBuffer` is of size `n_steps * n_envs = 557`, after every 8 untruncated mini-batches, there will be a truncated mini-batch of size 45
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=557 and n_envs=1)
  warnings.warn(


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Logging to training/Logs/PPO_25
----------------------------
| time/              |     |
|    fps             | 298 |
|    iterations      | 1   |
|    time_elapsed    | 1   |
|    total_timesteps | 557 |
----------------------------
-------------------------------------------
| time/                   |               |
|    fps                  | 96            |
|    iterations           | 2             |
|    time_elapsed         | 11            |
|    total_timesteps      | 1114          |
| train/                  |               |
|    approx_kl            | 0.00041670373 |
|    clip_fraction        | 0             |
|    clip_range           | 0.2           |
|    entropy_loss         | -8.32         |
|    explained_variance   | -6.22e-05     |
|    learning_rate        | 1.23e-05      |
|    loss                 | 1.21e+04      |
|    n_updates

[I 2024-06-08 12:09:58,861] Trial 2 finished with value: 1000.0 and parameters: {'n_steps': 557, 'learning_rate': 1.2271354804737577e-05}. Best is trial 1 with value: 1600.0.
/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py:145: UserWarning: You have specified a mini-batch size of 64, but because the `RolloutBuffer` is of size `n_steps * n_envs = 562`, after every 8 untruncated mini-batches, there will be a truncated mini-batch of size 50
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=562 and n_envs=1)
  warnings.warn(


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Logging to training/Logs/PPO_26
----------------------------
| time/              |     |
|    fps             | 306 |
|    iterations      | 1   |
|    time_elapsed    | 1   |
|    total_timesteps | 562 |
----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 98           |
|    iterations           | 2            |
|    time_elapsed         | 11           |
|    total_timesteps      | 1124         |
| train/                  |              |
|    approx_kl            | 0.0025966924 |
|    clip_fraction        | 0.00667      |
|    clip_range           | 0.2          |
|    entropy_loss         | -8.32        |
|    explained_variance   | -0.00515     |
|    learning_rate        | 2.36e-05     |
|    loss                 | 104          |
|    n_updates            | 

[I 2024-06-08 12:12:56,282] Trial 3 finished with value: 0.0 and parameters: {'n_steps': 562, 'learning_rate': 2.359283929931024e-05}. Best is trial 1 with value: 1600.0.
/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py:145: UserWarning: You have specified a mini-batch size of 64, but because the `RolloutBuffer` is of size `n_steps * n_envs = 735`, after every 11 untruncated mini-batches, there will be a truncated mini-batch of size 31
We recommend using a `batch_size` that is a factor of `n_steps * n_envs`.
Info: (n_steps=735 and n_envs=1)
  warnings.warn(


Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
Logging to training/Logs/PPO_27
----------------------------
| time/              |     |
|    fps             | 294 |
|    iterations      | 1   |
|    time_elapsed    | 2   |
|    total_timesteps | 735 |
----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 93           |
|    iterations           | 2            |
|    time_elapsed         | 15           |
|    total_timesteps      | 1470         |
| train/                  |              |
|    approx_kl            | 0.0009957528 |
|    clip_fraction        | 0            |
|    clip_range           | 0.2          |
|    entropy_loss         | -8.32        |
|    explained_variance   | -0.00117     |
|    learning_rate        | 1.11e-05     |
|    loss                 | 1.61e+04     |
|    n_updates            | 

[I 2024-06-08 12:15:10,664] Trial 4 finished with value: 4500.0 and parameters: {'n_steps': 735, 'learning_rate': 1.114058628197845e-05}. Best is trial 4 with value: 4500.0.


In [74]:
env.close()