In [1]:
! pip3 install gym==0.21.0
! pip3 install gym-retro==0.8.0
#! pip3 install opencv-python==4.6.0.66
#! pip3 install stable-baselines3==1.7.0

In [2]:
import retro

In [3]:
! python3 -m retro.import .

Importing StreetFighterIISpecialChampionEdition-Genesis
Imported 1 games


In [4]:
retro.data.list_games()

['1942-Nes',
 '1943-Nes',
 '3NinjasKickBack-Genesis',
 '8Eyes-Nes',
 'AaahhRealMonsters-Genesis',
 'AbadoxTheDeadlyInnerWar-Nes',
 'AcceleBrid-Snes',
 'ActRaiser2-Snes',
 'ActionPachio-Snes',
 'AddamsFamily-GameBoy',
 'AddamsFamily-Genesis',
 'AddamsFamily-Nes',
 'AddamsFamily-Sms',
 'AddamsFamily-Snes',
 'AddamsFamilyPugsleysScavengerHunt-Nes',
 'AddamsFamilyPugsleysScavengerHunt-Snes',
 'AdvancedBusterhawkGleylancer-Genesis',
 'Adventure-Atari2600',
 'AdventureIsland-GameBoy',
 'AdventureIsland3-Nes',
 'AdventureIslandII-Nes',
 'AdventuresOfBatmanAndRobin-Genesis',
 'AdventuresOfBayouBilly-Nes',
 'AdventuresOfDinoRiki-Nes',
 'AdventuresOfDrFranken-Snes',
 'AdventuresOfKidKleets-Snes',
 'AdventuresOfMightyMax-Genesis',
 'AdventuresOfMightyMax-Snes',
 'AdventuresOfRockyAndBullwinkleAndFriends-Genesis',
 'AdventuresOfRockyAndBullwinkleAndFriends-Nes',
 'AdventuresOfRockyAndBullwinkleAndFriends-Snes',
 'AdventuresOfStarSaver-GameBoy',
 'AdventuresOfYogiBear-Snes',
 'AeroFighters-Snes',
 

In [12]:
# creating our game environment

env = retro.make(game="StreetFighterIISpecialChampionEdition-Genesis")

In [6]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [7]:
env.action_space

MultiBinary(12)

In [8]:
env.action_space.sample()

array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0], dtype=int8)

In [17]:
import time

obs = env.reset() # Reset game to starting state

done = False # Set flag to flase, tells us when we dies
for game in range(1): # play one game 
    while not done: 
        if done: 
            obs = env.reset() # when we do die, we start the game again
        env.render()
        obs, reward, done, info = env.step(env.action_space.sample()) # randomly take action
        time.sleep(0.01)
        if reward > 0:
            print(reward) # only a number when win, no rewards when getting along which makes it hard to train rl agent - sparse rewards
        # need to change this, as the spare rewards will make it hard to train the rl agent

500.0
100.0
500.0
500.0
500.0
1500.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
1000.0
500.0
300.0
100.0
500.0
1000.0
500.0
500.0
500.0
500.0
1000.0
500.0
1500.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
100.0
1000.0
1000.0
10000.0
100.0
100.0
500.0
300.0
500.0


In [18]:
info

{'continuetimer': 10,
 'enemy_matches_won': 2,
 'enemy_health': 0,
 'health': 0,
 'matches_won': 0,
 'score': 27400}

In [23]:
env.close()

In [ ]:
#! pip3 install opencv-python==4.6.0.66

In [20]:
from gym import Env
from gym.spaces import MultiBinary, Box
import numpy as np # to calculate the delta between the frames
import cv2 # for grayscaling


Next steps to preprocess the environment
- Observation Preprocess - grayscale, frame delta, resize the frame so we have less pixels
- Filter the action - parameter 
- Reward function - set this to the score

In [21]:
# Creating custom environment that will carry out all the steps
# we pass our pass environment

# Code reference: https://github.com/nicknochnack/StreetFighterRL

class StreetFighter(Env): 
    def __init__(self):
        super().__init__()
        # Specify action space and observation space 
        # resizing and making gray scale
        self.observation_space = Box(low=0, high=255, shape=(84, 84, 1), dtype=np.uint8) 
        self.action_space = MultiBinary(12)
        # Startup and instance of the game 
        # additional parameter to filter only valid actions
        self.game = retro.make(game='StreetFighterIISpecialChampionEdition-Genesis', use_restricted_actions=retro.Actions.FILTERED)
    
    def reset(self):
        # Return the first frame 
        obs = self.game.reset()
        obs = self.preprocess(obs) 
        self.previous_frame = obs # want to also keep track of the previous frame to calculate a delta between the frames
        
        # Create a attribute to hold the score delta 
        self.score = 0 
        return obs
    
    def preprocess(self, observation): 
        # Grayscaling 
        gray = cv2.cvtColor(observation, cv2.COLOR_BGR2GRAY)
        # Resize 
        resize = cv2.resize(gray, (84,84), interpolation=cv2.INTER_CUBIC)
        # Add the channels value
        channels = np.reshape(resize, (84,84,1))
        return channels 
    
    def step(self, action): 
        # Take a step 
        obs, reward, done, info = self.game.step(action)
        obs = self.preprocess(obs) 
        
        # Frame delta - use this to train our agent
        frame_delta = obs - self.previous_frame
        self.previous_frame = obs 
        
        # Reshape the reward function
        reward = info['score'] - self.score 
        self.score = info['score'] 
        
        return frame_delta, reward, done, info
    
    def render(self, *args, **kwargs):
        self.game.render()
        
    def close(self):
        self.game.close()

In [24]:
env = StreetFighter()

In [25]:
env.observation_space

Box([[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]], [[[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 ...

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]

 [[255]
  [255]
  [255]
  ...
  [255]
  [255]
  [255]]], (84, 84, 1), uint8)

In [26]:
env.action_space.sample()

array([0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1], dtype=int8)

In [27]:
import time

obs = env.reset() # Reset game to starting state

done = False # Set flag to flase, tells us when we dies
for game in range(1): # play one game 
    while not done: 
        if done: 
            obs = env.reset() # when we do die, we start the game again
        env.render()
        obs, reward, done, info = env.step(env.action_space.sample()) # randomly take action
        time.sleep(0.01)
        if reward > 0:
            print(reward) # only a number when win, no rewards when getting along which makes it hard to train rl agent - sparse rewards
        # need to change this, as the spare rewards will make it hard to train the rl agent

2024-06-08 10:57:12.378 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabaf4db2a0>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 10:57:12.379 python[12151:36719507] Warning: Expected min height of view: (<NSButton: 0x7faba8c5bf00>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 10:57:12.383 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7faba8b71100>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 10:57:12.385 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7faba8b77330>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.


100
1000
500
500
300
300
300


KeyboardInterrupt: 

In [28]:
env.close()

In [ ]:
! pip3 install stable-baselines3==1.7.0

In [ ]:
! pip3 install torch torchvision

In [30]:
from stable_baselines3 import PPO

In [31]:
env = StreetFighter() # to create our preprocessed environment
model = PPO("CnnPolicy", env, verbose=1) # creating the model

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


In [32]:
# train the AI model on n steps

timesteps = 1000
model.learn(total_timesteps=timesteps)

-----------------------------
| time/              |      |
|    fps             | 311  |
|    iterations      | 1    |
|    time_elapsed    | 6    |
|    total_timesteps | 2048 |
-----------------------------


In [33]:
# save the model
model.save(f"training/models/PPO_{timesteps}_SF")

In [34]:
del model

In [39]:
env.close()

In [ ]:
# evaluate the model
from stable_baselines3.common.evaluation import evaluate_policy

# create environment
env = StreetFighter()
model = PPO.load(f"training/models/PPO_1000_SF")
mean_reward, _ = evaluate_policy(model, env, render=True, n_eval_episodes=5)



/opt/miniconda3/envs/street-fighter/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
2024-06-08 11:17:59.155 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabad280340>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 11:17:59.156 python[12151:36719507] Warning: Expected min height of view: (<NSButton: 0x7fabad63ae10>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.
2024-06-08 11:17:59.159 python[12151:36719507] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7fabad63dbd0>) to be less tha

In [ ]:
mean_reward